Removed calculator and added mapping unit tests
phyos-engineering/SurgView pull request #3
Opened 2021-06-15 21:42 UTC by danfu-phyos

The mapping tests pass the Circle CI build. Tests adding, existence, and updating key:coordinate pairs

2021-06-15 21:45 UTC, phyos-engineering commented on .idea/workspace.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Modify your .gitignore file in your local repo and make it ignore the .idea folder.

2021-06-15 21:49 UTC, phyos-engineering commented on test_mapping.py
> +        mapper = mapping.ScreenMap()
Also assert for other possible results.

2021-06-15 21:55 UTC, phyos-engineering commented on test_mapping.py
> +        mapper = mapping.ScreenMap()
Think about other possibilities. What if there's already another widget stored in the map? Would assert return true?

2021-06-15 22:15 UTC, phyos-engineering requested changes
See comments in files. 

We can't run integration tests because some methods are acting funky (expected). We'll talk about tracking and fixing these issues on Saturday!

2021-06-15 22:15 UTC, phyos-engineering commented on test_mapping.py
> +        mapper = mapping.ScreenMap()
Merge this into test_key_exists()

2021-06-15 22:15 UTC, phyos-engineering commented on test_mapping.py
> +        mapper = mapping.ScreenMap()
Would the assert work if there's more than one key-value pair in the map? What if the arguments were of different data types?

2021-06-17 18:56 UTC, dfu5823 commented on .idea/workspace.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Modified the .gitignore file to include the following:

# Created by https://www.toptal.com/developers/gitignore/api/pycharm
# Edit at https://www.toptal.com/developers/gitignore?templates=pycharm

### PyCharm ###
# Covers JetBrains IDEs: IntelliJ, RubyMine, PhpStorm, AppCode, PyCharm, CLion, Android Studio, WebStorm and Rider
# Reference: https://intellij-support.jetbrains.com/hc/en-us/articles/206544839

# User-specific stuff
.idea/**/workspace.xml
.idea/**/tasks.xml
.idea/**/usage.statistics.xml
.idea/**/dictionaries
.idea/**/shelf

# Generated files
.idea/**/contentModel.xml

# Sensitive or high-churn files
.idea/**/dataSources/
.idea/**/dataSources.ids
.idea/**/dataSources.local.xml
.idea/**/sqlDataSources.xml
.idea/**/dynamic.xml
.idea/**/uiDesigner.xml
.idea/**/dbnavigator.xml

# Gradle
.idea/**/gradle.xml
.idea/**/libraries

# Gradle and Maven with auto-import
# When using Gradle or Maven with auto-import, you should exclude module files,
# since they will be recreated, and may cause churn.  Uncomment if using
# auto-import.
# .idea/artifacts
# .idea/compiler.xml
# .idea/jarRepositories.xml
# .idea/modules.xml
# .idea/*.iml
# .idea/modules
# *.iml
# *.ipr

# CMake
cmake-build-*/

# Mongo Explorer plugin
.idea/**/mongoSettings.xml

# File-based project format
*.iws

# IntelliJ
out/

# mpeltonen/sbt-idea plugin
.idea_modules/

# JIRA plugin
atlassian-ide-plugin.xml

# Cursive Clojure plugin
.idea/replstate.xml

# Crashlytics plugin (for Android Studio and IntelliJ)
com_crashlytics_export_strings.xml
crashlytics.properties
crashlytics-build.properties
fabric.properties

# Editor-based Rest Client
.idea/httpRequests

# Android studio 3.1+ serialized cache file
.idea/caches/build_file_checksums.ser

### PyCharm Patch ###
# Comment Reason: https://github.com/joeblau/gitignore.io/issues/186#issuecomment-215987721

# *.iml
# modules.xml
# .idea/misc.xml
# *.ipr

# Sonarlint plugin
# https://plugins.jetbrains.com/plugin/7973-sonarlint
.idea/**/sonarlint/

# SonarQube Plugin
# https://plugins.jetbrains.com/plugin/7238-sonarqube-community-plugin
.idea/**/sonarIssues.xml

# Markdown Navigator plugin
# https://plugins.jetbrains.com/plugin/7896-markdown-navigator-enhanced
.idea/**/markdown-navigator.xml
.idea/**/markdown-navigator-enh.xml
.idea/**/markdown-navigator/

# Cache file creation bug
# See https://youtrack.jetbrains.com/issue/JBR-2257
.idea/$CACHE_FILE$

# CodeStream plugin
# https://plugins.jetbrains.com/plugin/12206-codestream
.idea/codestream.xml

# End of https://www.toptal.com/developers/gitignore/api/pycharm

2021-06-17 19:27 UTC, dfu5823 commented on test_mapping.py
> +        mapper = mapping.ScreenMap()
test if widget does not exist with the method:
    def test_key_nonexists(self):
        mapper = mapping.ScreenMap()
        print("Checking if Key -> test exists:")
        assert mapper.if_widget_exists("test") == False
if the key is an int it can't be created because: 
    def add_widget(self, key: str, x: int, y: int):
        """
        Add widget to map
        :param key: Key name of key value pair
        :param x: X coordinate of widget
        :param y: Y coordinate of widget
        """
        self.gui_map[key] = {"x": x, "y": y}

2021-06-17 19:29 UTC, dfu5823 commented on test_mapping.py
> +        mapper = mapping.ScreenMap()
I thought testing for other argument types was unnecessary because the method will not work unless the correct arguments are passed in. For instance:



    def add_widget(self, key: str, x: int, y: int):
        """
        Add widget to map
        :param key: Key name of key value pair
        :param x: X coordinate of widget
        :param y: Y coordinate of widget
        """
        self.gui_map[key] = {"x": x, "y": y}


will not add a widget unless a string and two ints are passed in as parameters -- is that right?

2021-06-17 19:30 UTC, phyos-engineering commented on .idea/workspace.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Awesome! Good job! On to the next task!

2021-06-17 19:32 UTC, dfu5823 commented on test_mapping.py
> +        mapper = mapping.ScreenMap()
If you want to add a widget but there's already another widget with the same key, it depends on the implementation of the dictionary. The dictionary may say that multiple values associated with one key are not allowed, for instance.

2021-06-17 20:06 UTC, dfu5823 commented on test_mapping.py
> +        mapper = mapping.ScreenMap()
I am able to add keys that are ints using add_widget. Is this supposed to happen? For instance, this returns true/passed
<img width="377" alt="Screen Shot 2021-06-17 at 1 06 18 PM" src="https://user-images.githubusercontent.com/71274065/122465308-930e9480-cf7d-11eb-9639-aad8db9bb441.png">

2021-06-17 20:07 UTC, phyos-engineering commented on test_mapping.py
> +        mapper = mapping.ScreenMap()
Why don't you try changing the add_widget() argument types in main() in mapping.py. The result will surprise you ;). Are we super sure that foo: <data_type> type checks?  Look into python type hints. Doing tons of LeetCode problems built a bad habit which I tend to forget when alternating between between Java/C++/Python.  How can we enforce a type check in python?

This is all an exercise! So this was done deliberately :) 

Clue:

So if I would add another key pair to the dict (2 key pairs in total), and assert mapping.gui_map would return the **entire** map. Would the entire map be equal {'test': {'x': 1, 'y': 2}}?

2021-06-17 20:14 UTC, phyos-engineering commented on test_mapping.py
> +        mapper = mapping.ScreenMap()
You're on to something! :) Read about python type hints. How can we enforce type checking in python? 

This is an exercise! Testing is also about finding flaws in the codebase (which you'll fix soon).

2021-06-17 20:37 UTC, phyos-engineering commented on test_mapping.py
> +        mapper = mapping.ScreenMap()
Looking good here!

2021-06-17 20:40 UTC, phyos-engineering commented on .idea/workspace.xml
>  <project version="4">
I think it's unfortunately still not ignoring your .idea folder. Why don't you manually remove via the github website and then do a git add .     and see what happens?

2021-06-17 20:52 UTC, phyos-engineering commented on test_mapping.py
> +        mapper = mapping.ScreenMap()
Ok, awesome! Get_map() is a void function so that's expected. Doesn't returning **mapper.gui_map()** kinda do the same thing as get_map? Would you say it's necessary?

2021-06-20 16:18 UTC, dfu5823 commented on test_mapping.py
> +        mapper = mapping.ScreenMap()
The methods in the codebase only give type hints, but don't enforce type checking, which you can do with mypy or isinstance(my_var,class). I think it's easier to enforce type checking in the codebase than the unit tests

2021-06-20 16:19 UTC, dfu5823 commented on .idea/workspace.xml
>  <project version="4">
I wasn't sure how to manually remove via github but I just added the .idea/ folder to the .gitignore

2021-06-20 16:27 UTC, dfu5823 commented on test_mapping.py
> +        mapper = mapping.ScreenMap()
Usually you use getters when the class object (in this case mapper) is private and you want to encapsulate the class object. In python, private variables in python aren't hidden fields. You may still want to have a getter to ensure data encapsulation. Not sure why get_map() does not actually return the map.

2021-06-20 16:56 UTC, danfu-phyos commented on .idea/workspace.xml
>  <project version="4">
Update: I manually removed via github and now I think the .idea is ignored

2021-06-21 21:35 UTC, phyos-engineering commented on test_mapping.py
> +        mapper = mapping.ScreenMap()
So get_map() just prints the list, so you really can't capture the output in a traditional variable (hence why it's void). Good observations regarding Python fields and getters/setters! There's a way to make them private in Python but it's not Pythonic.

2021-06-21 21:36 UTC, phyos-engineering commented on .idea/workspace.xml
>  <project version="4">
Yep! Just saw.

2021-06-21 21:41 UTC, phyos-engineering commented on test_mapping.py
> +        mapper = mapping.ScreenMap()
Yep! That's it! Good job dan! Yep, exactly! That's the goal. You'll personally modify mapping.py to start, write the unit tests, integration test (not all combinations are possible but you get the drift). Will explain more tomorrow.

2021-06-21 21:45 UTC, phyos-engineering approved these changes

2021-06-21 21:45 UTC, merged