Need to handle type checks
phyos-engineering/SurgView pull request #4
Opened 2021-06-20 16:54 UTC by danfu-phyos

Need to handle type checks, possibly in mapping.py

2021-06-20 17:01 UTC, danfu-phyos commented
Not sure how we want to implement type checks in the repo -- we could use assert isinstance(my_var,class) or we could use a try: except block or some other method

2021-06-21 21:25 UTC, phyos-engineering requested changes

2021-06-21 21:25 UTC, phyos-engineering commented on .circleci/config.yml
> +# Python CircleCI 2.0 configuration file
Motivations?

2021-06-21 21:25 UTC, phyos-engineering commented on calculator.py
> +"""
I think "git add . " accidentally added this. We can delete this.

2021-06-21 21:25 UTC, phyos-engineering commented on test_calculator.py
> +"""
Same as above. We can delete this from repo.

2021-06-21 21:52 UTC, phyos-engineering approved these changes

2021-06-21 21:57 UTC, phyos-engineering commented on .circleci/config.yml
> +# Python CircleCI 2.0 configuration file
Wait, just saw a red flag. It seems this commit overwrote cov=mapping with cov=calculator which I'm guessing wasn't intentional

2021-06-21 21:58 UTC, merged